# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cd3a9938c3af4aacb89493519f319b723bce7978b9b4e3aa1c5b94c2101bb4cb892106580e70bc1104c099efa6ee33554400e8f18f7abd5fe483b06ca13aa18

test:
  secret_key_base: f7593afc40be416a43889154a31386a17cc7f7eac91c3c521cb918c580b4a0e2ff5596408f2101c7a00175873fa0032bca4dc82ae9e54912adeddad74ed8d561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
